// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1XSFq1Mv89eubhLJbiwR5hjRqGuKIY6I',
    appId: '1:73912330168:web:73b35c9527b9c850aa114d',
    messagingSenderId: '73912330168',
    projectId: 'captura-lens-b870c',
    authDomain: 'captura-lens-b870c.firebaseapp.com',
    storageBucket: 'captura-lens-b870c.appspot.com',
    measurementId: 'G-L63TQM5Z56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsfURRNtCPgrvaYzZXdEvlA-9jzo_lOiQ',
    appId: '1:73912330168:android:d7b5249be11dc0a9aa114d',
    messagingSenderId: '73912330168',
    projectId: 'captura-lens-b870c',
    storageBucket: 'captura-lens-b870c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNEv9c1m-DGOLjfKgDYpdtKtyb7pOY2Lo',
    appId: '1:73912330168:ios:c7d1c58323731000aa114d',
    messagingSenderId: '73912330168',
    projectId: 'captura-lens-b870c',
    storageBucket: 'captura-lens-b870c.appspot.com',
    iosBundleId: 'com.example.capturaLens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNEv9c1m-DGOLjfKgDYpdtKtyb7pOY2Lo',
    appId: '1:73912330168:ios:b470f4f26a7d70afaa114d',
    messagingSenderId: '73912330168',
    projectId: 'captura-lens-b870c',
    storageBucket: 'captura-lens-b870c.appspot.com',
    iosBundleId: 'com.example.capturaLens.RunnerTests',
  );
}
